[package]
name = "westworld-bevy-ecs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.5.0"
bevy_app = "0.5.0"
bevy_log = "0.5.0"
