[package]
name = "westworld2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
game_state_machine = "1.0.0"
rand = "0.8.3"
